// <auto-generated />
namespace Real_Estate_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingRealtionToListing11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingRealtionToListing11));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301245408_addingRealtionToListing11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
