// <auto-generated />
namespace Real_Estate_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingSummaryFeatureColumnToListing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingSummaryFeatureColumnToListing));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301613572_AddingSummaryFeatureColumnToListing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
